version: '3'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    ports:
      - '3090:3090'
    environment:
      - 'GF_SECURITY_ADMIN_PASSWORD=yourpassword' # Change this to your desired password
    volumes:
      - ./grafana:/var/lib/grafana

