apiVersion: v1
kind: Namespace
metadata:
  name: newrelic

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nri-kubernetes-config
  namespace: newrelic
data:
  nri-kubernetes.yml: |
    integration_name: com.newrelic.kubernetes
    instances:
      - cluster_name: "k8-temp-cluster"

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: newrelic-infra
  namespace: newrelic
  labels:
    app: newrelic-infra
spec:
  selector:
    matchLabels:
      app: newrelic-infra
  template:
    metadata:
      labels:
        app: newrelic-infra
    spec:
      serviceAccountName: newrelic-infra
      containers:
        - name: newrelic-infra
          image: newrelic/infrastructure:latest
          env:
            - name: NRIA_LICENSE_KEY
              value: "eu01xxf49d26f27644a2cb7a6e5a0d9661eeNRAL"
            - name: NRIA_CUSTOM_ATTRIBUTES
              value: '{"cluster_name":"k8-temp-cluster"}'
          volumeMounts:
            - name: host-sys
              mountPath: /host/sys
              readOnly: true
            - name: host-dev
              mountPath: /host/dev
              readOnly: true
            - name: proc
              mountPath: /host/proc
              readOnly: true
            - name: run
              mountPath: /host/run
              readOnly: true
            - name: var-run
              mountPath: /var/run
            - name: host-root
              mountPath: /host/root
              readOnly: true
            - name: newrelic-config
              mountPath: /etc/newrelic-infra/integrations.d
              readOnly: true
      volumes:
        - name: host-sys
          hostPath:
            path: /sys
        - name: host-dev
          hostPath:
            path: /dev
        - name: proc
          hostPath:
            path: /proc
        - name: run
          hostPath:
            path: /run
        - name: var-run
          hostPath:
            path: /var/run
        - name: host-root
          hostPath:
            path: /
        - name: newrelic-config
          configMap:
            name: nri-kubernetes-config

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: newrelic-infra
  namespace: newrelic
