version: '3.8'
services:
  ggml:
    build:
      context: .
      dockerfile: Dockerfile.devcontainer
    image: ggml-devcontainer-image
    container_name: ggml-devcontainer
    volumes:
      - ../cpp/ggml:/ggml
    tty: true

# Using this docker compose file
# docker-compose -f docker-compose.devcontainer.yml up --build