version: '3'

services:

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - 9042:9042
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M
    volumes:
      - ../volumes/cassandra:/var/lib/cassandra
      - ../config/cassandra/cassandra.yaml:/etc/cassandra/cassandra.yaml
    restart: always


volumes:
  cassandra_data:
    driver: local
