version: '3'

services:
  # mysql:
  #   image: mysql
  #   container_name: mysqldb
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: 'ahmed'
  #     MYSQL_USER: 'ahmed'
  #     MYSQL_PASSWORD: 'password'
  #     MYSQL_ROOT_PASSWORD: 'ahmed'
  #     MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  #     MYSQL_AUTHENTICATION_PLUGIN: 'ahmed' 
  #   ports:
  #     - '3306:3306'
  #   expose:
  #     - '3306'
  #   volumes:
  #     - ../volumes/mysql:/var/lib/mysql
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.1'
  #         memory: 256M
  
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ggimdalbit
      MYSQL_DATABASE: system
      MYSQL_USER: admin
      MYSQL_PASSWORD: ggimdalbit
    ports:
      - "3306:3306"
    volumes:
      - ../volumes/mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M


