version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ../volumes/pg:/etc/tmp/gp
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 150M