version: '3'

services:
  prometheus:
    container_name: prometheus 
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ../config/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M


networks:
  monitoring:
    driver: bridge

volumes:
  prometheus:
    driver: local
