version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ../config/redis:/etc/redis/
    ports:
      - "6379:6379"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M

  redis-commander-cs2:
    container_name: redis-commander-cs2
    hostname: redis-commander-cs2
    image: ghcr.io/joeferner/redis-commander:latest
    build: .
    restart: always
    environment:
      - REDIS_LABEL=CS2
      - REDIS_HOST=${REDIS_AVR_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "8085:8081"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
  
  redis-commander-localhost:
    container_name: redis-commander-localhost
    hostname: redis-commander-localhost
    image: ghcr.io/joeferner/redis-commander:latest
    build: .
    restart: always
    environment:
      - REDIS_LABEL=Local
      - REDIS_HOST=host.docker.internal
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "8086:8081"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M