version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: wordpress-db-mysql
    volumes:
      - ../volumes/db_data_mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: example_user_password

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "8000:80" # Change the host port as needed
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: example_user_password
      WORDPRESS_DB_NAME: wordpress

volumes:
  db_data_mysql:
